/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StackRouteImport } from './routes/stack'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as NewRouteImport } from './routes/new'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as StackShareRouteImport } from './routes/$stackShare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as GuidesSplatRouteImport } from './routes/guides/$'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as BlogSplatRouteImport } from './routes/blog/$'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiPreviewRouteImport } from './routes/api/preview'

const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const StackShareRoute = StackShareRouteImport.update({
  id: '/$stackShare',
  path: '/$stackShare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSplatRoute = GuidesSplatRouteImport.update({
  id: '/guides/$',
  path: '/guides/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSplatRoute = BlogSplatRouteImport.update({
  id: '/blog/$',
  path: '/blog/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewRoute = ApiPreviewRouteImport.update({
  id: '/api/preview',
  path: '/api/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$stackShare': typeof StackShareRoute
  '/analytics': typeof AnalyticsRoute
  '/compare': typeof CompareRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/new': typeof NewRoute
  '/showcase': typeof ShowcaseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stack': typeof StackRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/stats': typeof ApiStatsRoute
  '/blog/$': typeof BlogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/guides/$': typeof GuidesSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$stackShare': typeof StackShareRoute
  '/analytics': typeof AnalyticsRoute
  '/compare': typeof CompareRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/new': typeof NewRoute
  '/showcase': typeof ShowcaseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stack': typeof StackRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/stats': typeof ApiStatsRoute
  '/blog/$': typeof BlogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/guides/$': typeof GuidesSplatRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$stackShare': typeof StackShareRoute
  '/analytics': typeof AnalyticsRoute
  '/compare': typeof CompareRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/new': typeof NewRoute
  '/showcase': typeof ShowcaseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stack': typeof StackRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/stats': typeof ApiStatsRoute
  '/blog/$': typeof BlogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/guides/$': typeof GuidesSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$stackShare'
    | '/analytics'
    | '/compare'
    | '/llms.txt'
    | '/mcp'
    | '/new'
    | '/showcase'
    | '/sitemap.xml'
    | '/stack'
    | '/api/preview'
    | '/api/stats'
    | '/blog/$'
    | '/docs/$'
    | '/guides/$'
    | '/blog/'
    | '/docs/'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$stackShare'
    | '/analytics'
    | '/compare'
    | '/llms.txt'
    | '/mcp'
    | '/new'
    | '/showcase'
    | '/sitemap.xml'
    | '/stack'
    | '/api/preview'
    | '/api/stats'
    | '/blog/$'
    | '/docs/$'
    | '/guides/$'
    | '/blog'
    | '/docs'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/$stackShare'
    | '/analytics'
    | '/compare'
    | '/llms.txt'
    | '/mcp'
    | '/new'
    | '/showcase'
    | '/sitemap.xml'
    | '/stack'
    | '/api/preview'
    | '/api/stats'
    | '/blog/$'
    | '/docs/$'
    | '/guides/$'
    | '/blog/'
    | '/docs/'
    | '/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StackShareRoute: typeof StackShareRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CompareRoute: typeof CompareRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  McpRoute: typeof McpRoute
  NewRoute: typeof NewRoute
  ShowcaseRoute: typeof ShowcaseRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StackRoute: typeof StackRoute
  ApiPreviewRoute: typeof ApiPreviewRoute
  ApiStatsRoute: typeof ApiStatsRoute
  BlogSplatRoute: typeof BlogSplatRoute
  DocsSplatRoute: typeof DocsSplatRoute
  GuidesSplatRoute: typeof GuidesSplatRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$stackShare': {
      id: '/$stackShare'
      path: '/$stackShare'
      fullPath: '/$stackShare'
      preLoaderRoute: typeof StackShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$': {
      id: '/guides/$'
      path: '/guides/$'
      fullPath: '/guides/$'
      preLoaderRoute: typeof GuidesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$': {
      id: '/blog/$'
      path: '/blog/$'
      fullPath: '/blog/$'
      preLoaderRoute: typeof BlogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview': {
      id: '/api/preview'
      path: '/api/preview'
      fullPath: '/api/preview'
      preLoaderRoute: typeof ApiPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StackShareRoute: StackShareRoute,
  AnalyticsRoute: AnalyticsRoute,
  CompareRoute: CompareRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  McpRoute: McpRoute,
  NewRoute: NewRoute,
  ShowcaseRoute: ShowcaseRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StackRoute: StackRoute,
  ApiPreviewRoute: ApiPreviewRoute,
  ApiStatsRoute: ApiStatsRoute,
  BlogSplatRoute: BlogSplatRoute,
  DocsSplatRoute: DocsSplatRoute,
  GuidesSplatRoute: GuidesSplatRoute,
  BlogIndexRoute: BlogIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
