import { ProjectConfigSchema, type ProjectConfig } from "@better-fullstack/types";

const DEFAULT_CONFIG = {
  projectName: "test-app",
  projectDir: "/tmp/test-app",
  relativePath: "test-app",
  ecosystem: "typescript",
  database: "sqlite",
  orm: "drizzle",
  backend: "hono",
  runtime: "bun",
  frontend: ["tanstack-router"],
  addons: [],
  examples: [],
  auth: "none",
  payments: "none",
  git: false,
  packageManager: "bun",
  versionChannel: "stable",
  install: false,
  dbSetup: "none",
  api: "trpc",
  webDeploy: "none",
  serverDeploy: "none",
  astroIntegration: "none",
  ai: "none",
  effect: "none",
  stateManagement: "none",
  forms: "react-hook-form",
  testing: "vitest",
  email: "none",
  cssFramework: "tailwind",
  uiLibrary: "none",
  mobileNavigation: "none",
  mobileUI: "none",
  mobileStorage: "none",
  mobileTesting: "none",
  mobilePush: "none",
  mobileOTA: "none",
  mobileDeepLinking: "none",
  shadcnBase: "radix",
  shadcnStyle: "nova",
  shadcnIconLibrary: "lucide",
  shadcnColorTheme: "neutral",
  shadcnBaseColor: "neutral",
  shadcnFont: "inter",
  shadcnRadius: "default",
  validation: "zod",
  realtime: "none",
  jobQueue: "none",
  animation: "none",
  fileUpload: "none",
  logging: "none",
  observability: "none",
  featureFlags: "none",
  analytics: "none",
  cms: "none",
  caching: "none",
  i18n: "none",
  search: "none",
  fileStorage: "none",
  rustWebFramework: "none",
  rustFrontend: "none",
  rustOrm: "none",
  rustApi: "none",
  rustCli: "none",
  rustLibraries: [],
  rustLogging: "tracing",
  rustErrorHandling: "anyhow-thiserror",
  rustCaching: "none",
  rustAuth: "none",
  pythonWebFramework: "none",
  pythonOrm: "none",
  pythonValidation: "none",
  pythonAi: [],
  pythonAuth: "none",
  pythonApi: "none",
  pythonTaskQueue: "none",
  pythonGraphql: "none",
  pythonQuality: "none",
  goWebFramework: "none",
  goOrm: "none",
  goApi: "none",
  goCli: "none",
  goLogging: "none",
  goAuth: "none",
  javaWebFramework: "none",
  javaBuildTool: "none",
  javaOrm: "none",
  javaAuth: "none",
  javaLibraries: [],
  javaTestingLibraries: [],
  elixirWebFramework: "none",
  elixirDatabase: "none",
  elixirLibraries: [],
  elixirTesting: [],
  aiDocs: [],
};

export function makeConfig(overrides: Partial<ProjectConfig> = {}): ProjectConfig {
  return ProjectConfigSchema.parse({
    ...DEFAULT_CONFIG,
    ...overrides,
  }) as ProjectConfig;
}
