import z from "zod";

import {
  AddonsSchema,
  AISchema,
  APISchema,
  AnalyticsSchema,
  AnimationSchema,
  AiDocsSchema,
  AstroIntegrationSchema,
  AuthSchema,
  BackendSchema,
  CachingSchema,
  CMSSchema,
  CSSFrameworkSchema,
  DatabaseSchema,
  DatabaseSetupSchema,
  DirectoryConflictSchema,
  EcosystemSchema,
  EffectSchema,
  EmailSchema,
  ElixirDatabaseSchema,
  ElixirLibrariesSchema,
  ElixirTestingSchema,
  ElixirWebFrameworkSchema,
  ExamplesSchema,
  FeatureFlagsSchema,
  FileStorageSchema,
  FileUploadSchema,
  FormsSchema,
  MobileDeepLinkingSchema,
  MobileNavigationSchema,
  MobileOTASchema,
  MobilePushSchema,
  MobileStorageSchema,
  MobileTestingSchema,
  MobileUISchema,
  FrontendSchema,
  GoApiSchema,
  GoAuthSchema,
  GoCliSchema,
  GoLoggingSchema,
  GoOrmSchema,
  GoWebFrameworkSchema,
  JavaAuthSchema,
  JavaBuildToolSchema,
  JavaLibrariesSchema,
  JavaOrmSchema,
  JavaTestingLibrariesSchema,
  JavaWebFrameworkSchema,
  I18nSchema,
  JobQueueSchema,
  LoggingSchema,
  ObservabilitySchema,
  ORMSchema,
  PackageManagerSchema,
  PaymentsSchema,
  ProjectNameSchema,
  PythonAiSchema,
  PythonApiSchema,
  PythonAuthSchema,
  PythonGraphqlSchema,
  PythonOrmSchema,
  PythonQualitySchema,
  PythonTaskQueueSchema,
  PythonValidationSchema,
  PythonWebFrameworkSchema,
  RealtimeSchema,
  RuntimeSchema,
  RustApiSchema,
  RustAuthSchema,
  RustCachingSchema,
  RustCliSchema,
  RustErrorHandlingSchema,
  RustFrontendSchema,
  RustLibrariesSchema,
  RustLoggingSchema,
  RustOrmSchema,
  RustWebFrameworkSchema,
  SearchSchema,
  ServerDeploySchema,
  ShadcnBaseColorSchema,
  ShadcnBaseSchema,
  ShadcnColorThemeSchema,
  ShadcnFontSchema,
  ShadcnIconLibrarySchema,
  ShadcnRadiusSchema,
  ShadcnStyleSchema,
  StateManagementSchema,
  TemplateSchema,
  TestingSchema,
  UILibrarySchema,
  ValidationSchema,
  VersionChannelSchema,
  WebDeploySchema,
} from "./types";

export const CreateCommandOptionsSchema = z.object({
  template: TemplateSchema.optional().describe("Use a predefined template"),
  yes: z.boolean().optional().default(false).describe("Use default configuration"),
  yolo: z
    .boolean()
    .optional()
    .default(false)
    .describe("(WARNING - NOT RECOMMENDED) Bypass validations and compatibility checks"),
  verbose: z.boolean().optional().default(false).describe("Show detailed result information"),
  dryRun: z
    .boolean()
    .optional()
    .default(false)
    .describe("Preview generated file tree without writing to disk"),
  ecosystem: EcosystemSchema.optional().describe(
    "Language ecosystem (typescript, react-native, rust, python, go, java, or elixir)",
  ),
  database: DatabaseSchema.optional(),
  orm: ORMSchema.optional(),
  auth: AuthSchema.optional(),
  payments: PaymentsSchema.optional(),
  email: EmailSchema.optional(),
  fileUpload: FileUploadSchema.optional(),
  effect: EffectSchema.optional(),
  stateManagement: StateManagementSchema.optional(),
  validation: ValidationSchema.optional(),
  forms: FormsSchema.optional(),
  testing: TestingSchema.optional(),
  ai: AISchema.optional(),
  realtime: RealtimeSchema.optional(),
  jobQueue: JobQueueSchema.optional(),
  animation: AnimationSchema.optional(),
  logging: LoggingSchema.optional(),
  observability: ObservabilitySchema.optional(),
  featureFlags: FeatureFlagsSchema.optional().describe("Feature flags provider"),
  analytics: AnalyticsSchema.optional().describe("Privacy-focused analytics"),
  cms: CMSSchema.optional().describe("Headless CMS solution"),
  caching: CachingSchema.optional().describe("Caching solution"),
  i18n: I18nSchema.optional().describe("Internationalization (i18n) library"),
  search: SearchSchema.optional().describe("Search engine solution"),
  fileStorage: FileStorageSchema.optional().describe("File storage solution (S3, R2)"),
  mobileNavigation: MobileNavigationSchema.optional().describe("Mobile navigation (expo-router, react-navigation)"),
  mobileUI: MobileUISchema.optional().describe("Mobile UI (tamagui, gluestack-ui, uniwind, unistyles)"),
  mobileStorage: MobileStorageSchema.optional().describe("Mobile storage (mmkv)"),
  mobileTesting: MobileTestingSchema.optional().describe("Mobile testing (maestro, react-native-testing-library)"),
  mobilePush: MobilePushSchema.optional().describe("Mobile push notifications (expo-notifications)"),
  mobileOTA: MobileOTASchema.optional().describe("Mobile OTA updates (expo-updates)"),
  mobileDeepLinking: MobileDeepLinkingSchema.optional().describe("Mobile deep linking (expo-linking)"),
  frontend: z.array(FrontendSchema).optional(),
  astroIntegration: AstroIntegrationSchema.optional().describe(
    "Astro UI framework integration (react, vue, svelte, solid)",
  ),
  addons: z.array(AddonsSchema).optional(),
  examples: z.array(ExamplesSchema).optional(),
  git: z.boolean().optional(),
  packageManager: PackageManagerSchema.optional(),
  install: z.boolean().optional(),
  versionChannel: VersionChannelSchema.optional().describe(
    "Dependency version channel (stable, latest, beta)",
  ),
  dbSetup: DatabaseSetupSchema.optional(),
  backend: BackendSchema.optional(),
  runtime: RuntimeSchema.optional(),
  api: APISchema.optional(),
  cssFramework: CSSFrameworkSchema.optional(),
  uiLibrary: UILibrarySchema.optional(),
  shadcnBase: ShadcnBaseSchema.optional().describe("shadcn/ui headless library (radix, base)"),
  shadcnStyle: ShadcnStyleSchema.optional().describe(
    "shadcn/ui visual style (vega, nova, maia, lyra, mira)",
  ),
  shadcnIconLibrary: ShadcnIconLibrarySchema.optional().describe(
    "shadcn/ui icon library (lucide, tabler, hugeicons, phosphor, remixicon)",
  ),
  shadcnColorTheme: ShadcnColorThemeSchema.optional().describe(
    "shadcn/ui color theme (neutral, blue, violet, etc.)",
  ),
  shadcnBaseColor: ShadcnBaseColorSchema.optional().describe(
    "shadcn/ui base neutral color (neutral, stone, zinc, gray)",
  ),
  shadcnFont: ShadcnFontSchema.optional().describe("shadcn/ui font (inter, geist, figtree, etc.)"),
  shadcnRadius: ShadcnRadiusSchema.optional().describe(
    "shadcn/ui border radius (default, none, small, medium, large)",
  ),
  webDeploy: WebDeploySchema.optional(),
  serverDeploy: ServerDeploySchema.optional(),
  directoryConflict: DirectoryConflictSchema.optional(),
  renderTitle: z.boolean().optional(),
  disableAnalytics: z.boolean().optional().default(false).describe("Disable analytics"),
  manualDb: z
    .boolean()
    .optional()
    .default(false)
    .describe("Skip automatic/manual database setup prompt and use manual setup"),
  rustWebFramework: RustWebFrameworkSchema.optional().describe(
    "Rust web framework (axum, actix-web)",
  ),
  rustFrontend: RustFrontendSchema.optional().describe("Rust WASM frontend (leptos, dioxus)"),
  rustOrm: RustOrmSchema.optional().describe("Rust ORM/database (sea-orm, sqlx)"),
  rustApi: RustApiSchema.optional().describe("Rust API layer (tonic, async-graphql)"),
  rustCli: RustCliSchema.optional().describe("Rust CLI tools (clap, ratatui)"),
  rustLibraries: z.array(RustLibrariesSchema).optional().describe("Rust core libraries"),
  rustLogging: RustLoggingSchema.optional().describe("Rust logging (tracing, env-logger)"),
  rustErrorHandling: RustErrorHandlingSchema.optional().describe(
    "Rust error handling (anyhow-thiserror, eyre)",
  ),
  rustCaching: RustCachingSchema.optional().describe("Rust caching (moka, redis)"),
  rustAuth: RustAuthSchema.optional().describe("Rust auth (oauth2)"),
  pythonWebFramework: PythonWebFrameworkSchema.optional().describe(
    "Python web framework (fastapi, django)",
  ),
  pythonOrm: PythonOrmSchema.optional().describe("Python ORM/database (sqlalchemy, sqlmodel)"),
  pythonValidation: PythonValidationSchema.optional().describe("Python validation (pydantic)"),
  pythonAi: z.array(PythonAiSchema).optional().describe("Python AI/ML frameworks"),
  pythonAuth: PythonAuthSchema.optional().describe("Python auth library (authlib, jwt)"),
  pythonApi: PythonApiSchema.optional().describe(
    "Python API framework (django-rest-framework, django-ninja)",
  ),
  pythonTaskQueue: PythonTaskQueueSchema.optional().describe("Python task queue (celery)"),
  pythonGraphql: PythonGraphqlSchema.optional().describe(
    "Python GraphQL framework (strawberry)",
  ),
  pythonQuality: PythonQualitySchema.optional().describe(
    "Python code quality (ruff, mypy, pyright)",
  ),
  goWebFramework: GoWebFrameworkSchema.optional().describe("Go web framework (gin, echo, fiber)"),
  goOrm: GoOrmSchema.optional().describe("Go ORM/database (gorm, sqlc)"),
  goApi: GoApiSchema.optional().describe("Go API layer (grpc-go)"),
  goCli: GoCliSchema.optional().describe("Go CLI tools (cobra, bubbletea, urfave-cli)"),
  goLogging: GoLoggingSchema.optional().describe("Go logging (zap, zerolog, slog)"),
  goAuth: GoAuthSchema.optional().describe("Go auth (casbin, jwt)"),
  javaWebFramework: JavaWebFrameworkSchema.optional().describe(
    "Java web framework (spring-boot, quarkus, none)",
  ),
  javaBuildTool: JavaBuildToolSchema.optional().describe("Java build tool (maven, gradle, none)"),
  javaOrm: JavaOrmSchema.optional().describe("Java ORM/database (spring-data-jpa)"),
  javaAuth: JavaAuthSchema.optional().describe("Java auth (spring-security)"),
  javaLibraries: z
    .array(JavaLibrariesSchema)
    .optional()
    .describe("Java application libraries"),
  javaTestingLibraries: z
    .array(JavaTestingLibrariesSchema)
    .optional()
    .describe("Java testing libraries"),
  elixirWebFramework: ElixirWebFrameworkSchema.optional().describe(
    "Elixir web framework (phoenix, none)",
  ),
  elixirDatabase: ElixirDatabaseSchema.optional().describe("Elixir database layer (ecto, none)"),
  elixirLibraries: z
    .array(ElixirLibrariesSchema)
    .optional()
    .describe("Elixir application libraries"),
  elixirTesting: z.array(ElixirTestingSchema).optional().describe("Elixir testing libraries"),
  aiDocs: z
    .array(AiDocsSchema)
    .optional()
    .describe("AI documentation files (claude-md, agents-md, cursorrules)"),
});

export const CreateCommandInputSchema = z.tuple([
  ProjectNameSchema.optional(),
  CreateCommandOptionsSchema,
]);
